# RENAME FILE TO 'config.yml'
bot:
  token: XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXXXXXXXXXXX-XXXXXXXXXXX
  owner_ids:
    - 554487514011009035
  prefix: $
  default_bet: 100
  bonus_multiplier: 50 # bonus = default_bet * multiplier
  bonus_cooldown: 3 # Bonus every x hours
